/*
 * Trieda menu vytvára základné rozhranie pre uźivateľa, kde si nastaví farbu
 * hráča, jeho protivník tiež a následne sa prostrednictvom tlačítka spúšťa celá Hra... So Simple ;)   
 */
package strielackadavo;

import strielackadavo.hra.Hra;

/**
 *
 * @author Pavličko.D
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        this.setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboHrac2 = new javax.swing.JComboBox<>();
        jComboHrac1 = new javax.swing.JComboBox<>();
        btnHraj = new javax.swing.JButton();
        jLabelHrac2 = new javax.swing.JLabel();
        jLabelHrac1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Strieľačka by Davo");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vyber si farbu hráčov", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gabriola", 0, 18))); // NOI18N

        jComboHrac2.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        jComboHrac2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "vyber farbu...", "red", "yellow", "blue", "magenta", "black" }));
        jComboHrac2.setName(""); // NOI18N
        jComboHrac2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboHrac2ActionPerformed(evt);
            }
        });

        jComboHrac1.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        jComboHrac1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "vyber farbu...", "red", "yellow", "blue", "magenta", "black" }));
        jComboHrac1.setName(""); // NOI18N
        jComboHrac1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboHrac1ActionPerformed(evt);
            }
        });

        btnHraj.setFont(new java.awt.Font("Gabriola", 1, 36)); // NOI18N
        btnHraj.setText("HRAJ !");
        btnHraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHrajActionPerformed(evt);
            }
        });

        jLabelHrac2.setFont(new java.awt.Font("Gabriola", 1, 36)); // NOI18N
        jLabelHrac2.setText("Hráč 2");

        jLabelHrac1.setFont(new java.awt.Font("Gabriola", 1, 36)); // NOI18N
        jLabelHrac1.setText("Hráč 1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabelHrac2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelHrac1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jComboHrac2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jComboHrac1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(btnHraj, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHrac2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHrac1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboHrac2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboHrac1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnHraj, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jComboHrac2.getAccessibleContext().setAccessibleName("");
        jLabelHrac1.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboHrac2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboHrac2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboHrac2ActionPerformed
    
    /**
     * Metóda, ktorá spúšťa celú hru zo základneho meníčka,
     * kde si povyberáte farby a následne kliknete na tlačitko HRAŤ !
     * @param evt 
     */
    private void btnHrajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHrajActionPerformed
        String farbaHraca1 = jComboHrac1.getSelectedItem().toString();
        String farbaHraca2 = jComboHrac2.getSelectedItem().toString();
        
        if (!farbaHraca1.equals("vyber farbu...") && !farbaHraca2.equals("vyber farbu...")) {
            Hra hra = new Hra(farbaHraca1, farbaHraca2);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnHrajActionPerformed

    private void jComboHrac1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboHrac1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboHrac1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHraj;
    private javax.swing.JComboBox<String> jComboHrac1;
    private javax.swing.JComboBox<String> jComboHrac2;
    private javax.swing.JLabel jLabelHrac1;
    private javax.swing.JLabel jLabelHrac2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
